modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/MattCzyr/EnderMail/issues"
license="CC BY-NC-SA 4.0"
[[mods]]
    modId="endermail"
    version="1.20-1.2.8"
    displayName="Ender Mail"
    displayURL="https://github.com/MattCzyr/EnderMail"
    authors="ChaosTheDude"
    description='''
    Employ Endermen to deliver packages anywhere in the world.
    '''
[[dependencies.endermail]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.endermail]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20]"
    ordering="NONE"
    side="BOTH"
